{{- range $i := until (.Values.control_plane.node_count | int) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.cluster_name }}-cp-{{ $i }}-cloudinit
  namespace: {{ $.Values.cluster_namespace }}
stringData:
  userdata: |
    #cloud-config
    {{- if eq $.Values.vm.distro "rocky" }}
    package_update: true
    package_upgrade: true
    packages:
      - qemu-guest-agent
      - cloud-utils-growpart
      - python3
      - curl
    {{- else if $.Values.vm.qemu_agent_install }}
    package_update: true
    packages:
      - qemu-guest-agent
    {{- end }}
    {{- if and (eq $.Values.vm.distro "rocky") $.Values.ssh_pub_key }}
    users:
      - name: rocky
        sudo: "ALL=(ALL) NOPASSWD:ALL"
        groups:
          - wheel
        shell: /bin/bash
        ssh_authorized_keys:
          - {{ $.Values.ssh_pub_key }}
    {{- end }}
    write_files:
    {{- if $.Values.addons.cert_manager.enabled }}
    - path: /var/lib/rancher/rke2/server/manifests/{{ default "certmanager.yaml" $.Values.addons.cert_manager.manifest_name }}
      owner: root
      content: |
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cert-manager
          namespace: default
        spec:
          bootstrap: true
          targetNamespace: {{ $.Values.addons.cert_manager.namespace }}
          createNamespace: {{ $.Values.addons.cert_manager.create_namespace }}
{{- if $.Values.addons.cert_manager.airgap.enabled }}
          chartContent: {{ $.Values.addons.cert_manager.airgap.chartContent | quote }}
{{- else }}
          repo: {{ $.Values.addons.cert_manager.repo }}
          chart: {{ $.Values.addons.cert_manager.chart }}
          version: {{ $.Values.addons.cert_manager.version }}
{{- end }}
{{- if $.Values.addons.cert_manager.values }}
          valuesContent: |-
{{ $.Values.addons.cert_manager.values | indent 12 }}
{{- end }}
    {{- end }}
    {{- if $.Values.addons.rancher.enabled }}
    - path: /var/lib/rancher/rke2/server/manifests/{{ default "rancher.yaml" $.Values.addons.rancher.manifest_name }}
      owner: root
      content: |
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: rancher
          namespace: default
        spec:
          bootstrap: false
          targetNamespace: {{ $.Values.addons.rancher.namespace }}
          createNamespace: {{ $.Values.addons.rancher.create_namespace }}
{{- if $.Values.addons.rancher.airgap.enabled }}
          chartContent: {{ $.Values.addons.rancher.airgap.chartContent | quote }}
{{- else }}
          repo: {{ $.Values.addons.rancher.repo }}
          chart: {{ $.Values.addons.rancher.chart }}
          version: {{ $.Values.addons.rancher.version }}
{{- end }}
          set:
            hostname: {{ $.Values.addons.rancher.hostname }}
            replicas: {{ $.Values.addons.rancher.replicas }}
            bootstrapPassword: {{ $.Values.addons.rancher.bootstrapPassword }}
{{- if $.Values.addons.rancher.additionalSet }}
{{ $.Values.addons.rancher.additionalSet | toYaml | indent 12 }}
{{- end }}
{{- if $.Values.addons.rancher.values }}
          valuesContent: |-
{{ $.Values.addons.rancher.values | indent 12 }}
{{- end }}
    {{- end }}
    {{- if $.Values.control_plane.files }}
{{ $.Values.control_plane.files | toYaml | indent 4 }}
    {{- end }}
    - path: /etc/rancher/rke2/config.yaml
      owner: root
      content: |
        token: {{ $.Values.shared_token }}
        {{- if ne $i 0 }}
        server: https://{{ $.Values.control_plane.vip }}:9345
        {{- end }}
        system-default-registry: {{ $.Values.system_default_registry }}
        tls-san:
          - {{ $.Values.cluster_name }}-cp-{{ $i }}
          - {{ $.Values.control_plane.vip }}
{{- range $.Values.tls_san_extra }}
          - {{ . }}
{{- end }}
        secrets-encryption: true
        write-kubeconfig-mode: 0640
        use-service-account-credentials: true
    {{- if hasKey $.Values "registry_config" }}
    - path: /etc/rancher/rke2/registries.yaml
      owner: root
      content: |-
{{ $.Values.registry_config | toYaml | indent 8 }}
    {{- end }}
    - path: /etc/hosts
      owner: root
      content: |
        127.0.0.1 localhost
        127.0.0.1 {{$.Values.cluster_name }}-cp-{{ $i }}
    runcmd:
    {{- if $.Values.vm.qemu_agent_enable }}
    - - systemctl
      - enable
      - '--now'
      - qemu-guest-agent.service
    {{- end }}
    {{- if not $.Values.vm.airgapped_image }}
    - mkdir -p /var/lib/rancher/rke2-artifacts && curl -sfL https://get.rke2.io -o /var/lib/rancher/install.sh && chmod +x /var/lib/rancher/install.sh
    {{- end}}
    - INSTALL_RKE2_VERSION={{ $.Values.rke2_version }} INSTALL_RKE2_TYPE="server" /var/lib/rancher/install.sh
    - systemctl enable rke2-server.service
    - useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
    - systemctl start rke2-server.service
    ssh_authorized_keys: 
    - {{ $.Values.ssh_pub_key }}
  {{- if ne $.Values.control_plane.ipam "dhcp" }}
  {{- if hasKey $.Values.control_plane "network" }}
  networkdata: |
{{ index $.Values.control_plane.network $i | indent 4 }}
  {{- end}}
  {{- else}}
  networkdata: ""
  {{- end}}
{{- end}}
