{{- $lbNamespace := default "default" $.Values.cluster_namespace -}}
{{- $poolName := printf "%s-%s-pool" $lbNamespace $.Values.cluster_name -}}
---
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: {{ $poolName }}
spec:
  ranges:
    - gateway: {{ .Values.control_plane.loadbalancer_gateway }}
      rangeEnd: {{ .Values.control_plane.vip }}
      rangeStart: {{ .Values.control_plane.vip }}
      subnet: {{ .Values.control_plane.loadbalancer_subnet }}
  selector: {}
---
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: LoadBalancer
metadata:
  name: {{ .Values.cluster_name }}-lb
  namespace: {{ $lbNamespace }}
  {{- if $.Values.network_name }}
  annotations:
    loadbalancer.harvesterhci.io/network: {{ $.Values.network_name }}
  {{- end }}
spec:
  {{- if $.Values.network_name }}
  network: {{ $.Values.network_name }}
  {{- end }}
  healthCheck:
    failureThreshold: 2
    port: 6443
    successThreshold: 3
    timeoutSeconds: 5
    periodSeconds: 5
  ipam: pool
  ipPool: {{ $poolName }}
  listeners:
    - name: k8s-api
      port: 6443
      protocol: TCP
      backendPort: 6443
    - name: ingress
      port: 443
      protocol: TCP
      backendPort: 443
    - name: join
      port: 9345
      protocol: TCP
      backendPort: 9345
  workloadType: vm
  backendServerSelector:
    harvesterhci.io/vmName:
    {{- range $i := until (.Values.control_plane.node_count | int)}}
    - {{ $.Values.cluster_name }}-cp-{{ $i }}
    {{- end}}
